#!/bin/bash -eu

NUM_FILES_MOVED="$1"

function log () {
  echo "$( date )" >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

log "Notification is disabled for right now"

#if [ -r "/root/.deepMedicalAIPushoverCredentials" ] && [ $NUM_FILES_MOVED -gt 0 ]
#then
#  log "Sending Pushover message for moved files."
#
#  source /root/.deepMedicalAIPushoverCredentials
#
#  curl -F "token=$pushover_app_key" \
#  -F "user=$pushover_user_key" \
#  -F "title=Dashcam Copy Complete" \
#  -F "message=$NUM_FILES_MOVED file(s) were copied." \
#  https://api.pushover.net/1/messages
#fi